name = "TenNIS"
uuid = "1113fa09-e660-4d5c-afd9-bd16691d8c30"
version = "0.1.0"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[deps]
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"

[compat]
ITensorNetworks = "0.15.0"
julia = "1.10"
